### ISSUE TITLE
[BUG] [/memory]对话异常

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [shuakami/amyalmond_bot#10]
完整log: https://paste.ubuntu.com/p/z98xrzhhRQ/

我已经观察到很多次了，在长时间与AI对话时memory参数有概率会被直接加入对话框中，这很奇怪
是因为我开着debug模式吗，那也应该是一直都存在才对

**Comment by shuakami** [comment]
> 我已经观察到很多次了，在长时间与AI对话时memory参数有概率会被直接加入对话框中，这很奇怪 是因为我开着debug模式吗，那也应该是一直都存在才对

您可以提供一些比较具体的代码片段吗？关键部分使用粗体即可

**Comment by shuakami** [comment]
（我的意思是您的日志有些长，我好像没有办法找到您指的是哪个部分）

**Comment by xiaoyueyoqwq** [comment]
> （我的意思是您的日志有些长，我好像没有办法找到您指的是哪个部分）

uhm...你从头看起就知道了，我复制了最后一段时间正常时间段的日志+有问题的部分
![image](https://github.com/user-attachments/assets/cf6f706a-f423-4407-aa75-eaa72f417ae4)

**Comment by shuakami** [comment]
我理解了。
您可以查看[README](https://github.com/shuakami/amyalmond_bot/tree/develop#)中关于处理记忆的部分
```
消息处理与记忆
用户识别
当用户首次@机器人时，AmyAlmond 会提示用户输入昵称，并将其记录在data/user_names.json数据表中，确保在后续对话中能够识别并使用该昵称。

上下文管理
机器人会自动保存对话上下文，并针对当前对话生成最合适的响应。也会自动压缩上下文组合发送，尽量减少token。

长期记忆处理
机器人能够记录并在适当时机引用长期记忆中的信息。建议您在configs/system-prompt.txt中加入

* 你拥有内置工具。可以使用 <get memory> 获取你之前的记忆，你必须在有你认为重要的记忆时使用 <memory>内容</memory> 存储记忆。
以达到最佳效果。
```
![chrome_xg5HlbLdit](https://github.com/user-attachments/assets/c125e894-98bb-4924-9d2e-f23ffef02049)
![chrome_GHKBxW75Os](https://github.com/user-attachments/assets/2ab4e7ac-a495-49c4-a4a3-37d5ed49102e)
---
在prompt中，您应该告诉了机器人，可以使用<memory>内容</memory> 存储记忆，因此，当机器人认为认为重要的记忆时，就会使用<memory>内容</memory> 存储记忆。

存储的记忆会放置到您的长期记忆文件中。

**Comment by xiaoyueyoqwq** [comment]
> 我理解了。 您可以查看[README](https://github.com/shuakami/amyalmond_bot/tree/develop#)中关于处理记忆的部分
> 
> ```
> 消息处理与记忆
> 用户识别
> 当用户首次@机器人时，AmyAlmond 会提示用户输入昵称，并将其记录在data/user_names.json数据表中，确保在后续对话中能够识别并使用该昵称。
> 
> 上下文管理
> 机器人会自动保存对话上下文，并针对当前对话生成最合适的响应。也会自动压缩上下文组合发送，尽量减少token。
> 
> 长期记忆处理
> 机器人能够记录并在适当时机引用长期记忆中的信息。建议您在configs/system-prompt.txt中加入
> 
> * 你拥有内置工具。可以使用 <get memory> 获取你之前的记忆，你必须在有你认为重要的记忆时使用 <memory>内容</memory> 存储记忆。
> 以达到最佳效果。
> ```
> 
> ## ![chrome_xg5HlbLdit](https://private-user-images.githubusercontent.com/149454909/358906926-c125e894-98bb-4924-9d2e-f23ffef02049.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODYwMDYsIm5iZiI6MTcyMzk4NTcwNiwicGF0aCI6Ii8xNDk0NTQ5MDkvMzU4OTA2OTI2LWMxMjVlODk0LTk4YmItNDkyNC05ZDJlLWYyM2ZmZWYwMjA0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxMjU1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODAzODBmNWY4ZTgzYWEwZGVjY2VkMThlZmJiMjYxODE4NWRmZjg5NGU1ZmYxN2U3NzMwYjE0M2I0YzM4M2I4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C5elP8xEuH5wtiC_JqB2yHsobBxIJ7c48S-raKaKNKA)
> ![chrome_GHKBxW75Os](https://private-user-images.githubusercontent.com/149454909/358906963-2ab4e7ac-a495-49c4-a4a3-37d5ed49102e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODYwMDYsIm5iZiI6MTcyMzk4NTcwNiwicGF0aCI6Ii8xNDk0NTQ5MDkvMzU4OTA2OTYzLTJhYjRlN2FjLWE0OTUtNDljNC1hNGEzLTM3ZDVlZDQ5MTAyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxMjU1MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjljMDMzNzJhYzg5Y2Q3Yjg5ZTU0MmRjYWViOWEyMjQzOWRmOGMwMzhjNTEzNjYwYzdjZWQ4YzU5YzIzMWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xRfyZmTZwEwgo2LFP2ZYTBkd-2BAC3jgqvFxxX43wtI)
> 在prompt中，您应该告诉了机器人，可以使用内容 存储记忆，因此，当机器人认为认为重要的记忆时，就会使用内容 存储记忆。
> 
> 存储的记忆会被放置到您的长期记忆文件中。
> 
> 另外您的机器人似乎使用了不标准的记忆处理方式：[memory]内容[/memory]

uhm...我知道了，我会调整AI的提示词的
感谢帮助

**Comment by shuakami** [comment]
此功能还有待完善，我仍然在思考更好的处理方式。
请期待后续更新 <3

**Comment by xiaoyueyoqwq** [comment]
问题已经整合至[#17](https://github.com/shuakami/amyalmond_bot/issues/17)讨论
