### ISSUE TITLE
[FEATURE] 即将到来的插件拓展框架功能方案（如更多api支持等）

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [shuakami/amyalmond_bot#16]
那我就直话直说吧，OpenAI-HK的api感觉成本还是有点太高了，所以我一直在寻找更优质的解决方案
国内有很多公益api接口。也许我们可以考虑兼容一下？这个可以更方便下游开发者对模型进行调试等工作
（我已经给OpenAI-HK冲60块了

参考：https://api.aa1.cn/doc/gemini.html

**Comment by shuakami** [comment]
我靠 这么多...
~我好像迄今为止也就只冲了50~

好的，稍后会排期的！

**Comment by xiaoyueyoqwq** [comment]
> 我靠 这么多... ~我好像迄今为止也就只冲了50~
> 
> 好的，稍后会排期的！

![image](https://github.com/user-attachments/assets/a1c6f22b-9103-4613-8d52-b0df7b121fdd)

![Screenshot 2024-08-19 140546](https://github.com/user-attachments/assets/e8beb5e8-f023-4c80-96a2-d4cf65072f8a)

**Comment by xiaoyueyoqwq** [comment]
考虑到公益API的不稳定性，我会提供更多的一些选择
比较靠谱的：
https://openai-hk.com/docs/lab/free-api.html
https://github.com/chuyuewei/ChatGPT-API

未经测试或看起来不太稳定的：
https://api.aa1.cn/doc/gemini.html
https://copilot-chatgpt.com/14200.html
https://gitee.com/xianglan/free_gpt4
https://github.com/popjane/free_chatgpt_api

**Comment by shuakami** [comment]
已经看到了。

我之前尝试模块化LLM api 一直失败，后面就没敢动了。因为这个原因，此功能可能会延期上线。

**Comment by xiaoyueyoqwq** [comment]
> 已经看到了。
> 
> 我之前尝试模块化LLM api 一直失败，后面就没敢动了。因为这个原因，此功能可能会延期上线。

omg你猜猜我找到了什么
![image](https://github.com/user-attachments/assets/baeb2e08-bd4c-424d-97eb-0ed4661b521a)
我觉得我们以后可以放弃维护OpenAI-HK了，毕竟这个[模型](https://ngedlktfticp.cloud.sealos.io/)真的太便宜了（哭

**Comment by shuakami** [comment]
这个模型确实很便宜。

后续会考虑从文档中移除OpenAI-hk的推荐，但依然会支持（如果有）对应的请求方法。

**Comment by shuakami** [comment]
![Image](https://github.com/user-attachments/assets/8b365f9f-75c7-4ceb-9d55-d8977ddce44a)

您好，我查看了您给我的所有API的api文档，除了https://api.aa1.cn/doc/gemini.html无法支持（现在还没有图片功能）外，其他的接口好像都是可以直接使用的。我虽然只测试了HappyAPI，但一般来说，您只需要修改配置文件就可以兼容大部分api。

> 稍后（16:45-17:20）我会推送最新开发版，您可以更新测试一下。

**Comment by shuakami** [comment]
您好，最新开发版本已经推送

**Comment by xiaoyueyoqwq** [comment]
更新已经整合到Stable分支，此issue完成
