### ISSUE TITLE
[DM] 关于此项目memory储存方式的改进策略和长期维护（长期讨论帖）

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [shuakami/amyalmond_bot#17]
嗨，又见面了
这几天我一直在观察您的项目，我先对您对此项目做出的努力表达由衷的敬意，在这几天的使用开发和观察过程中我认为最大的问题还是在memory方向，特别是在某些极端情况下不正确的memory上下文记忆处理和储存可能导致严重的模型思维混乱；在此过程中我有一位朋友 [@MrHua269](https://github.com/MrHua269/) 对您的项目十分感兴趣，我希望可以帮您完善一下这个项目，最后感谢您一直以来对我下游调试做出的技术帮助

接下来所有改进方案您都可以直接与他进行沟通🚀

**Comment by shuakami** [comment]
好的。谢谢您的肯定。

不过我需要您（@xiaoyueyoqwq ）或者您朋友（[@MrHua269](https://github.com/MrHua269/)）的日程安排。这样我才能合理安排计划或任务。

谢谢您。

**Comment by xiaoyueyoqwq** [comment]
> 好的。谢谢您的肯定。
> 
> 不过我需要您（@xiaoyueyoqwq ）或者您朋友（[@MrHua269](https://github.com/MrHua269/)）的日程安排（就是大概什么时间段有空）。这样我才能合理安排计划或任务。
> 
> 谢谢您。

我不确定您是否能够接受，我朋友使用了java+kt混合多线程写了一个简单的bot，测试可以正常使用（但是模型温度貌似有点问题，没有目前我们这个项目的框架热情），最主要还是希望您能参考一下他的memory存储方式，这次修改他直接把所有用户的数据都进行了隔离，并以lmdb的格式存储在了专用文件夹内

附件: 
[AmyalmondBotKt.zip](https://github.com/user-attachments/files/16660434/AmyalmondBotKt.zip)

**Comment by shuakami** [comment]
我目前稍微查看了一下，这好像是在代码中使用的记忆逻辑：

首先是用了用户记忆分别存储（数据隔离）和持久化，这个实现很棒，但我的问题是 AmyAlmond_bot主要是为了**群聊聊天**所设计，使用分群组记忆可以让群员记忆之间有更多关联..而用户记忆分别存储似乎针对的更多是单人对话或角色扮演对话的处理方式。不过这种方式对我来说有一定的启发/很感谢您和您的朋友。

不过很抱歉的是，因为我个人对于Java的熟练度非常低。所以在以后的开发中可能仍然会使用Python作为主要语言。

过几天我可能会规划一份新的记忆逻辑重构计划。再次感谢您和您朋友提供的思路。

**Comment by shuakami** [comment]
https://marble-repair-490.notion.site/d8dfbc8218d841ae918a6ca19c94ecc0?v=09520b55e4f2447e9242b4c9338a1a25&pvs=4

您好，最新方案已经写出来了。
您可以告诉我您的意见

**Comment by xiaoyueyoqwq** [comment]
> https://marble-repair-490.notion.site/d8dfbc8218d841ae918a6ca19c94ecc0?v=09520b55e4f2447e9242b4c9338a1a25&pvs=4
> 
> 您好，最新方案已经写出来了。 您可以告诉我您的意见

我认为目前来说方案2较为稳定，可以先尝试使用方案2后再观察具体可能会消耗多少token

token消耗这个数值我目前测评出来的结果是有些许玄学，可能你生成一句5个字的对话回答消耗5000左右的token，但生成一句20字甚至30字的对话依旧消耗的是5000左右的token，我也不能具体查证中间到底是出了什么问题

顺便一提，关于数据隔离方面我们有考虑过群与群之间的数据隔离吗，目前我的bot还在测试阶段因此没有尝试过跨群处理数据，但是这方面的数据安全问题我依旧还是比较关心的

**Comment by shuakami** [comment]
![Image](https://github.com/user-attachments/assets/bf36b0c2-3aea-49b9-9dec-181dff9605c5)

群与群之间的数据安全我可以肯定，至少目前没有安全风险。

---

群A72FE39A6开头：
![Image](https://github.com/user-attachments/assets/39e2168a-8a70-45b5-a250-7ee4e8711cb7)
群 2D17A7F开头：
![Image](https://github.com/user-attachments/assets/144b4899-5511-46b6-9bd7-006aa8a79c06)

**Comment by shuakami** [comment]
> 我认为目前来说方案2较为稳定，可以先尝试使用方案2后再观察具体可能会消耗多少token
> 
> token消耗这个数值我目前测评出来的结果是有些许玄学，可能你生成一句5个字的对话回答消耗5000左右的token，但生成一句20字甚至30字的对话依旧消耗的是5000左右的token....

了解了您的意见，后面会出专门的计划的。但可能需要比较久的时间

**Comment by MrHua269** [comment]
emmm关于记忆错乱那个是因为有损压缩导致的（在memorymanager里那个compress的方法里让ai压缩记忆的），那个会导致对话与对话者关系缺失

**Comment by shuakami** [comment]
谢谢您指出问题。后续会优化此方法并加强压缩日志输出。

**Comment by shuakami** [comment]
一个好消息是：
已经敲定了最终架构，使用MongoDB + Milvus这样的架构。

如果运气好的话，大概3~9天可以出第一版测试版 <3

明天就开始开发

**Comment by xiaoyueyoqwq** [comment]
> 一个好消息是：
> 已经敲定了最终方案，使用MongoDB + Milvus这样的架构。
> 
> 如果运气好的话，大概3~9天可以出第一版测试版 <3
> 
> 明天就开始开发
> 
> 

Glad to hear that! 祝一切顺利👋

**Comment by shuakami** [comment]
您好。目前主要部分已经开发、测试完成了，还剩一些闲杂项。
如果不出意外的话，下午 15:00-18:00 这一个时间段将会发布开发版更新。
因为本次改动较大，建议您提前复制整个项目保存为压缩文件备份。

<3

**Comment by xiaoyueyoqwq** [comment]
> 您好。目前主要部分已经开发、测试完成了，还剩一些闲杂项。 如果不出意外的话，下午 15:00-18:00 这一个时间段将会发布开发版更新。 因为本次改动较大，建议您提前复制整个项目保存为压缩文件备份。
> 
> <3

辛苦，我会尽快跟进下游测试🚀

**Comment by shuakami** [comment]
您好，最新开发版已经推送。很抱歉晚了一些

**Comment by xiaoyueyoqwq** [comment]
> 您好，最新开发版已经推送。很抱歉晚了一些

没事，刚好我也在吃饭
稍候我会进行测试，刚好我刚刚在研究项目最近推出的插件模块，您有考虑过专门推出一份third-party插件开发文档吗？

**Comment by shuakami** [comment]
有写~ 但是好像不够详细而且很混沌...我先把前面的问题都解决了再写文档吧

**Comment by xiaoyueyoqwq** [comment]
> 有写~ 但是好像不够详细而且很混沌...我先把前面的问题都解决了再写文档吧

了解，这几天辛苦咯😇

**Comment by xiaoyueyoqwq** [comment]
> 有写~ 但是好像不够详细而且很混沌...我先把前面的问题都解决了再写文档吧

hi, 我刚才测试了一下并且发现了一个可能出现的缺漏：您可能没有及时更新develop分支的config.yaml，因为我在启动时被质询要求提供MongoDB数据库信息，但是我并不清楚该如何配置
![image](https://github.com/user-attachments/assets/259b323d-a901-4cc3-bfe4-fed30360573a)

**Comment by shuakami** [comment]
您可以运行core/db/setup/mongodb/mongodb_setup_configs.py和core/db/setup/elasticsearch/elasticsearch_configs.py

进行自动配置（前提是您已经安装）

**Comment by shuakami** [comment]
安装脚本在core/db/db_status_checker.py

**Comment by shuakami** [comment]
您可以使用`core/db/upgrade/db_upgrade.py`把您之前的数据恢复到新数据库架构中

**Comment by xiaoyueyoqwq** [comment]
> core/db/db_status_checker.py

我再尝试运行这几个脚本自动配置时我遇到了一个找不到的前置：core
之前所有报错缺失的前置我都通过pip install手动安装了，但貌似只有这个无法解决
![image](https://github.com/user-attachments/assets/694fbede-0851-4b85-9c25-2425ab774ef9)

**Comment by shuakami** [comment]
您好，我这边需要2-3小时的时间进行更新，您看这样可以吗

**Comment by xiaoyueyoqwq** [comment]
> 您好，我这边需要2-3小时的时间进行更新修复，您看这样可以吗

可以的，正好我这边的机器人上线审核被腾讯驳回了😡
对了，如果您有事情找我的话可以直接联系我这个邮箱xiaoyueyoqwq@outlook.com
祝您好运🤗

**Comment by shuakami** [comment]
很抱歉，可能要多加几天了。
现在我又发现了更加严重的恶性问题，正在紧急修复。

**Comment by xiaoyueyoqwq** [comment]
> 很抱歉，可能要多加几天了。
> 现在我又发现了更加严重的恶性问题，正在紧急修复。

没事，那这几天就得辛苦一下你咯😇

**Comment by shuakami** [comment]
您好，开发版更新 Version: 1.2.0 (Beta_824001) (PATCH 1)已推送。

您可以执行`tools/db_tools.py`

**Comment by xiaoyueyoqwq** [comment]
> tools/db_tools.py

嗨，早上好
我刚刚发现了一个错误，详细请看截图

![image](https://github.com/user-attachments/assets/40180d81-a08d-4199-b6bb-60cacc41c68f)

应该是在安装Elasticsearch时出现的语法错误？

**Comment by xiaoyueyoqwq** [comment]
> 您好，开发版更新 Version: 1.2.0 (Beta_824001) (PATCH 1)已推送。
> 
> 您可以更新后执行`tools/db_tools.py`进行操作

我刚才尝试手动复现了一下问题，您脚本步骤应该是按照CSDN上写的吧？那上面缺失了一个步骤，您可以按照这份教程修改以下脚本：https://cloud.tencent.com/developer/article/1657534

**Comment by shuakami** [comment]
您好，MongoDB安装脚本也会出现同样的问题吗？

**Comment by shuakami** [comment]
> 我刚才尝试手动复现了一下问题，您脚本步骤应该是按照CSDN上写的吧？那上面缺失了一个步骤，您可以按照这份教程修改以下脚本：https://cloud.tencent.com/developer/article/1657534

您好，已经尝试修复并推送
您可以下载：
[elasticsearch_install_p1.zip](https://github.com/user-attachments/files/16735440/elasticsearch_install.zip)

**Comment by xiaoyueyoqwq** [comment]
> > 我刚才尝试手动复现了一下问题，您脚本步骤应该是按照CSDN上写的吧？那上面缺失了一个步骤，您可以按照这份教程修改以下脚本：https://cloud.tencent.com/developer/article/1657534
> 
> 您好，已经尝试修复并推送 您可以下载： [elasticsearch_install_p1.zip](https://github.com/user-attachments/files/16735440/elasticsearch_install.zip)
> 
> 我的是参照`https://mirror.tuna.tsinghua.edu.cn/help/elasticsearch/`写的。实在是不太严谨，后续会使用虚拟机测试后再上线

已测试，应该没有大问题
记忆测试方面我貌似收到了一份关于append_to_long_term_memory的异常报告，您可以查看一下这份log
ALERT: 请在PC上打开此日志防止网页卡死https://paste.ubuntu.com/p/YqFtt4XQXM/

**Comment by shuakami** [comment]
这是遗留问题，我现在修复，稍后推送

**Comment by shuakami** [comment]
您好，最新版本已经推送

**Comment by xiaoyueyoqwq** [comment]
> 您好，最新修复已经推送

测试完毕，目前没有发现问题复现，我会一直追踪直到确认
不过我再次在log中收到了一份错误日志，并且这份日志也和memory有些许关系？因为我总是在相似的指令下频繁收到这个报错：https://paste.ubuntu.com/p/QMsH5tY6S5/

**Comment by shuakami** [comment]
您有更加详细的日志吗？DEBUG等级的

**Comment by xiaoyueyoqwq** [comment]
> 您有更加详细的日志吗？DEBUG等级的

稍等，我已经切换到debug模式尝试复现此问题了
稍后我会将更详细的日志放出

**Comment by xiaoyueyoqwq** [comment]
> 您有更加详细的日志吗？DEBUG等级的

嗨，很幸运地我很快就复现了此问题
日志如下：https://paste.ubuntu.com/p/HSvHrDy2hd/

**Comment by shuakami** [comment]
看起来像是您的OpenAI API 问题，我检查了一下您的payload，发现也没有问题。
建议您：
- 更换API提供商
- 增加`config.py`的`MAX_CONTEXT_TOKENS`
- 简化您的SystemPrompt

如果后续依然复现，您可以随时发给我

**Comment by xiaoyueyoqwq** [comment]
> 看起来像是您的OpenAI API 问题，我检查了一下您的payload，发现也没有问题。 建议您：
> 
> * 更换API提供商
> * 增加`config.py`的`MAX_CONTEXT_TOKENS`
> * 简化您的SystemPrompt
> 
> 如果后续依然复现，您可以随时发给我

了解，感谢您的帮助

**Comment by xiaoyueyoqwq** [comment]
> 看起来像是您的OpenAI API 问题，我检查了一下您的payload，发现也没有问题。
> 建议您：
> - 更换API提供商
> - 增加`config.py`的`MAX_CONTEXT_TOKENS`
> - 简化您的SystemPrompt
> 
> 如果后续依然复现，您可以随时发给我

memory测试报告：依旧需要改进

目前我所测试的长期记忆已经相当好了，但是需要注意的是我们貌似只保留了AI的长期记忆，这就导致AI在每一次回答时都会花费大量时间索引以往的所有memory，这可能会带来严重的io负担和大量数据碎片误导AI做出不正确的回答，我认为我们可以保留一下以前的记忆存储模式，将其分类的短期记忆和长期记忆处理

如果您有什么需要补充的欢迎提出

**Comment by shuakami** [comment]
我真的很高兴听到您说，目前所测试的长期记忆已经相当好了。
不过实际上目前的架构设计就是由MongoDB负责短期记忆，Elasticsearch负责长期记忆。

您的建议我会考虑的。很感谢您的测试反馈~

<3

**Comment by xiaoyueyoqwq** [comment]
> 我真的很高兴听到您说，目前所测试的长期记忆已经相当好了。
> 不过实际上目前的架构设计就是由MongoDB负责短期记忆，Elasticsearch负责长期记忆。
> 
> 您的建议我会考虑的。很感谢您的测试反馈~
> 
> <3

我看出来了，话说您愿意来实地记录一下情况吗，我愿意将最精准的情况实时分享给您，如果您愿意的话可以发邮件向我要即可

对了，我朋友待会也回来补充一点内容，稍候他就会来

**Comment by shuakami** [comment]
您好。实际上来说测试数据对于我来说非常有用，特别是在改进逻辑上。
您可以打包后邮件发送给我，谢谢您。

**Comment by xiaoyueyoqwq** [comment]
> 您好。实际上来说测试数据对于我来说非常有用，特别是在改进逻辑上。
> 您可以打包后邮件发送给我，谢谢您。

好的，很高兴能听到您这么说，哈哈

**Comment by MrHua269** [comment]
记忆丢失的问题在压缩上，其实可以搞个遗忘机制用来忘掉一些"热点"或者"权重"较低的记忆，索引可以按照你压缩记忆的办法生成一次然后按照遗忘机制忘记部分用来减轻记忆堆积

**Comment by shuakami** [comment]
> 记忆丢失的问题在压缩上，其实可以搞个遗忘机制用来忘掉一些"热点"或者"权重"较低的记忆，索引可以按照你压缩记忆的办法生成一次然后按照遗忘机制忘记部分用来减轻记忆堆积

您好。您的建议很有建设性，我会在之后的代码中结合此建议修改的

**Comment by MrHua269** [comment]
> > 记忆丢失的问题在压缩上，其实可以搞个遗忘机制用来忘掉一些"热点"或者"权重"较低的记忆，索引可以按照你压缩记忆的办法生成一次然后按照遗忘机制忘记部分用来减轻记忆堆积
> 
> 您好。您的建议很有建设性，我会在之后的代码中结合此建议修改的

主意强调ai记住话是谁说的，不要直接概括记忆而是分条并分出记忆被获取到频率然后按照频率低的删除，可以加一个遗忘机制，自动忘掉随机的调用频率在一定区间的记忆，记住一定要让ai知道话是谁说的

**Comment by shuakami** [comment]
您好。这是我为本项目重新搭建的[文档中心](https://tiancailuoxiaohei.notion.site/dfd73a088f7745d39244bbcecbbaf910?v=972fb97796534341aca87a165039a3b1&pvs=4)
您觉得怎么样

**Comment by xiaoyueyoqwq** [comment]
> 您好。这是我为本项目重新搭建的[文档中心](https://tiancailuoxiaohei.notion.site/dfd73a088f7745d39244bbcecbbaf910?v=972fb97796534341aca87a165039a3b1&pvs=4) 您觉得怎么样

很不错，辛苦了

**Comment by shuakami** [comment]
您好，最新开发版更新 Version: 1.2.0 (Beta_824001) 已推送。
建议您备份当前项目目录为压缩包后再更新哦 <3

**Comment by xiaoyueyoqwq** [comment]
> 您好，最新开发版更新 Version: 1.2.0 (Beta_826010) 已推送。
> 建议您备份当前项目目录为压缩包后再更新哦 <3

豪德，感谢提醒😇
对了 我想了解一下这次更新调整了哪些内容呢？我可以对此做出一些针对性测试

**Comment by shuakami** [comment]
主要是针对记忆系统的修改（提示词优化、支持记忆使用频率、定期调用该函数以遗忘低频率使用的记忆、修复错误的消息加载），还有优化了一下插件方面。

优化了Prompt：
```
  if token_count > MAX_CONTEXT_TOKENS:
            summary = await get_gpt_response(
                list(valid_message_history),
                "你是一个高级记忆管理算法。请在不忽略任何关键人物、数据或细节的情况下，将下列对话无损压缩为简明扼要的条目。每一条记忆请保持独立，明确记录说话者身份，并优先保留频率较高的重要信息。压缩后的结果应为一组分条列出的简要总结（每条20-40字），以确保关键信息不会丢失。注意：这些条目将用于进一步的记忆管理和遗忘机制，因此需要确保压缩后的信息依然具有高价值，并能有效减少低频次、不重要内容的堆积。"
            )
```

**Comment by xiaoyueyoqwq** [comment]
> 主要是针对记忆系统的修改（提示词优化、支持记忆使用频率、定期调用该函数以遗忘低频率使用的记忆、修复错误的消息加载），还有优化了一下插件方面。
> 
> 优化了Prompt：
> 
> ```python
>   if token_count > MAX_CONTEXT_TOKENS:
>             summary = await get_gpt_response(
>                 list(valid_message_history),
>                 "你是一个高级记忆管理算法。请在不忽略任何关键人物、数据或细节的情况下，将下列对话无损压缩为简明扼要的条目。每一条记忆请保持独立，明确记录说话者身份，并优先保留频率较高的重要信息。压缩后的结果应为一组分条列出的简要总结（每条20-40字），以确保关键信息不会丢失。注意：这些条目将用于进一步的记忆管理和遗忘机制，因此需要确保压缩后的信息依然具有高价值，并能有效减少低频次、不重要内容的堆积。"
>             )
> ```

hi, 我刚刚在测试启动过程中遇到了一个中断错误，详细请看截图
![image](https://github.com/user-attachments/assets/633b1cb5-d853-4bc4-b769-19d62368ec76)

**Comment by shuakami** [comment]
抱歉，是我忘记提交main.py的更新了，已推送

**Comment by xiaoyueyoqwq** [comment]
> 抱歉，是我忘记提交main.py的更新了，已推送

更新反馈：依旧存在问题
详细看图你就明白了

![Screenshot_20240826-214858.png](https://github.com/user-attachments/assets/026df47b-2357-417f-8a58-54775e9306ef)

我也不知道为什么，你有头绪吗🤔

**Comment by shuakami** [comment]
我建议回滚...但是只是回滚记忆，插件部分不回滚

**Comment by shuakami** [comment]
之后的话记忆逻辑不会大改了，只会做小调整

**Comment by xiaoyueyoqwq** [comment]
> 我建议回滚...但是只是回滚记忆逻辑，插件部分不回滚
> 
> 我明天弄吧

了解，我朋友也在研究这个问题，毕竟...有点太怪了不觉得吗🤔

**Comment by shuakami** [comment]
可以研究一下payload（您有日志可以发给我）

**Comment by xiaoyueyoqwq** [comment]
> 可以研究一下payload（您有日志可以发给我）

okay，我正在调整AI提示词来尽可能缓解此问题，目前我全程都开着debug等级日志，明早我会将今天晚上的所有测试结果和日志打包发给您

**Comment by shuakami** [comment]
辛苦了，注意休息



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月26日(周一) 晚上10:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shuakami/amyalmond_bot] [DM] 关于此项目memory储存方式的改进策略和长期维护（长期讨论帖） (Issue #17)




  
可以研究一下payload（您有日志可以发给我）
  
okay，我正在调整AI提示词来尽可能缓解此问题，目前我全程都开着debug等级日志，明早我会将今天晚上的所有测试结果和日志打包发给您

**Comment by xiaoyueyoqwq** [comment]
> 辛苦了，注意休息
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年8月26日(周一) 晚上10:25 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [shuakami/amyalmond_bot] [DM] 关于此项目memory储存方式的改进策略和长期维护（长期讨论帖） (Issue #17) 可以研究一下payload（您有日志可以发给我） okay，我正在调整AI提示词来尽可能缓解此问题，目前我全程都开着debug等级日志，明早我会将今天晚上的所有测试结果和日志打包发给您 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were assigned.Message ID: ***@***.***&gt;

完整日志：[botpy.zip](https://github.com/user-attachments/files/16756051/botpy.zip)

**Comment by shuakami** [comment]
> 顺便一说，我还是希望加入一个能一键清空数据库记忆的功能脚本，毕竟我也不确定目前我们的数据库可承载的数据量到底是多少，并且这样产生的一些碎片数据是否会得到自动整理等长期问题

您好，这个实际上是一直有的，但为了安全性一直没有上线推送。
[清空数据库.zip](https://github.com/user-attachments/files/16773431/default.zip)

**Comment by shuakami** [comment]
> 我知道这样的极限压力测试可能导致这样的问题发生，但如果发生了这样的问题我们有什么方法可以修复或重置数据库吗？亦或者通过类似热重启的方式释放一些记忆缓存？

您好，后续可能会使用一些方法对数据库进行优化或清理（如定时操作），包括引入前端可视化，自动修复数据库错误。
如果在目前出现问题您可以尝试清空数据库。

**Comment by xiaoyueyoqwq** [comment]
> > 我知道这样的极限压力测试可能导致这样的问题发生，但如果发生了这样的问题我们有什么方法可以修复或重置数据库吗？亦或者通过类似热重启的方式释放一些记忆缓存？
> 
> 您好，后续可能会使用一些方法对数据库进行优化或清理（如定时操作），包括引入前端可视化，自动修复数据库错误。
> 如果在目前出现问题您可以尝试清空数据库。

了解，目前我用的清空数据库的办法...有点暴力🤔也就是直接到mongosh删掉数据库，curl DELETE掉ES数据表和rm rf掉tmp里面的那个缓存文件，这样....应该没问题吧😇

**Comment by shuakami** [comment]
应该没有问题。会自动创建的

**Comment by shuakami** [comment]
> 我也不知道为什么，你有头绪吗🤔

您好，关于您反馈的这个问题可以尝试升级到最新`开发版更新 Version 1.2.3 (Alpha_829001)`，尝试修改了可能会导致此问题的一个记忆注入位置

**Comment by xiaoyueyoqwq** [comment]
> > 我也不知道为什么，你有头绪吗🤔
> 
> 您好，关于您反馈的这个问题可以尝试升级到最新`开发版更新 Version 1.2.3 (Alpha_829001)`，尝试修改了可能会导致此问题的一个记忆注入位置

反馈：上一份Beta测试版和着一份Alpha版我都测试过一遍了，先说结论：大概率是模型的问题

测试中Meta模型在8B 70B 405B三种模型下都出现了之前所提到的情况，但更换gpt-4o之后就没再出现过了，虽然gpt-4o相对情感表达方面没有其他模型好但是稳定性很不错

**Comment by shuakami** [comment]
但是如果聊天比较多的话4o还是很贵的

**Comment by shuakami** [comment]
我个人认为Gemini情感很棒

**Comment by xiaoyueyoqwq** [comment]
> 我个人认为Gemini情感很棒

的确如此，基于NLP的Gemini在先天体质和训练上就是向着更加“自然”的对话状态靠拢的，所以在情感表达方面比其他模型都要好很多；其实一开始我也是优先选择了Gemini作为基础模型和训练对象，一开始效果的确也很不错，但是我担心的事情还是发生了：因为我一直都是Google Pixel的资深用户，所以我日常所有语音助手和问答AI用的都是内置在Google应用里的Gemini，这个AI更像是一个短跑运动员，在初期的表现力远远超过其他AI模型，但是一旦用户与Gemini对话内容增多或对话时间过长Gemini就会呈现一种类似“精神分裂”的情况，并且反应时间也将持指数级增长（4000ms > 7000ms)，这一点我认为可能是NLP的先天性问题，因为我在日常使用Gemini的情况下也会遇到类似的情况发生，再加上Gemini本身部分（至少我们能用得起的）模型都是为**Pixel用户设计的**，并且使用了大量的Markdown排版格式，因此对于QQ纯文本聊天的排版非常不友好，可能会出现莫名其妙的空格，短句等排版问题，因此在后期我也是放弃了Gemini而寻找其他更稳定的解决方案

**Comment by shuakami** [comment]
是的 此问题我也遇到过

**Comment by shuakami** [comment]
> 我也不知道为什么，你有头绪
您好，关于您反馈的这个问题可以尝试升级到最新开发版更新 Version 1.2.4（Alpha_902002），尝试更新了记忆逻辑，详情请查看[commit](https://github.com/shuakami/amyalmond_bot/commit/fdb93970cb92cfcd004b02b66897fee13b4a7a68)

**Comment by xiaoyueyoqwq** [comment]
> > 我也不知道为什么，你有头绪吗🤔
> 
> 您好，关于您反馈的这个问题可以尝试升级到最新开发版更新 Version 1.2.4（Alpha_902002），尝试更新了记忆逻辑，详情请查看[commit](https://github.com/shuakami/amyalmond_bot/commit/fdb93970cb92cfcd004b02b66897fee13b4a7a68)

了解，我会在晚上合并更新

**Comment by xiaoyueyoqwq** [comment]
> > 我也不知道为什么，你有头绪吗🤔
> 
> 您好，关于您反馈的这个问题可以尝试升级到最新开发版更新 Version 1.2.4（Alpha_902002），尝试更新了记忆逻辑，详情请查看[commit](https://github.com/shuakami/amyalmond_bot/commit/fdb93970cb92cfcd004b02b66897fee13b4a7a68)

测试结果报告：出现致命错误
昨天晚上稍微有点忙就忘记了更新，不好意思；但是今天下午我同步了一下更新，但在启动过程中遇到了一个致命错误
不过幸运的是程序成功识别到了这个错误并且帮我打包了您所有可能需要的错误日志，详细请看[附件](https://github.com/user-attachments/files/16847235/amyalmond_bot.issue_error_20240903_181908.zip)

在此之前我已经例行完成了双清（好吧，我已经习惯这么叫了）数据库的操作，但依然收到了这个错误
并且您可以在文档中心提示一下该如何退出这个错误页面，反正目前我C+C按着没反应

**Comment by shuakami** [comment]
您好。是因为我没有上传最新的config.py导致的。但现在我已经进行了非常多的重构和修改（总体大概需要2天左右才能完成），如果现在给您似乎也没有作用了。所以推荐您手动在`config.py`（104行）中添加：

```python
MEMORY_BATCH_SIZE = test_config.get("memory_batch_size", 6)
# 在这一行的上面添加
REQUEST_TIMEOUT= test_config.get("request_timeout", 7)
```

**Comment by xiaoyueyoqwq** [comment]
> 您好。是因为我忘记更新config.py导致的。但现在我已经进行了非常多的重构和修改（总体大概需要2天左右才能完成），如果现在给您最新的`config.py`似乎也没有作用了。所以推荐您手动在`config.py`（104行）处添加：
> 
> ```python
> MEMORY_BATCH_SIZE = test_config.get("memory_batch_size", 6)
> # 在这一行的上面添加
> REQUEST_TIMEOUT= test_config.get("request_timeout", 7)
> ```

了解，不过我可以继续等待下一次更新合并再一起测试，期待您的作品
