### ISSUE TITLE
[BUG] 接入点可能需要更新

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [shuakami/amyalmond_bot#2]
先放log: https://paste.ubuntu.com/p/H7T3M9c6Wz/
---
一开始我尝试接入[免费GPT 3.5模型](https://github.com/chuyuewei/ChatGPT-API)时出现了点问题，我以为是适配问题于是更换成了文档中指定的api接口，但是发现依然不起作用后我去查阅了一下官方接口文档，发现他们最近更改了接口使用标准
![image](https://github.com/user-attachments/assets/a3132b6a-cbc9-4203-ac87-90799e71427d)
---
于是我开始尝试手动修正api接口，但是依然收到了日志中的错误，我也尝试过自行修复更改和替换过期的接口，但貌似并不起作用
![image](https://github.com/user-attachments/assets/aaf6042d-8d84-42c2-81ae-828ee3b613b6)
---
这是否是因为信息过期导致的api调用错误？我们是否要更新一下使用指南中的api？最后感谢您的回复

**Comment by shuakami** [comment]
您好，此问题我会在明天上午查看（今天太累了...），如给您带来不便还请谅解

**Comment by xiaoyueyoqwq** [comment]
> 您好，此问题我会在明天上午查看（今天太累了...），如给您带来不便还请谅解

没事，我尽量自己再看看是不是有什么初疏漏之类的
新项目嘛，理解理解

**Comment by shuakami** [comment]
1.请您检查，您使用的gpt-3.5接口是使用[https://github.com/chuyuewei/ChatGPT-API](https://github.com/chuyuewei/ChatGPT-API)的，还是[https://www.openai-hk.com/docs/getting-started.html](https://www.openai-hk.com/docs/getting-started.html)
这两个的文档和接入方式、API地址、秘钥似乎都是不同的
2.如果您使用的是[https://github.com/chuyuewei/ChatGPT-API](https://github.com/chuyuewei/ChatGPT-API)，我可能需要为您手动调整，带您确认后会进行排期。届时您可以先使用[https://www.openai-hk.com/docs/getting-started.html](https://www.openai-hk.com/docs/getting-started.html)进行替代
3.如果您使用的是OpenAI-HK和它的官方api以及秘钥，请等待下一个开发版本推送。在实际测试中没有出现问题。
![pycharm64_ZTwUE4Xzdk](https://github.com/user-attachments/assets/efd66b41-5bc3-41e1-ad95-d8d413f1161d)

**Comment by shuakami** [comment]
1.请您检查，您使用的gpt-3.5接口是使用[https://github.com/chuyuewei/ChatGPT-API](https://github.com/chuyuewei/ChatGPT-API)的，还是[https://www.openai-hk.com/docs/getting-started.html](https://www.openai-hk.com/docs/getting-started.html)
这两个的文档和接入方式、API地址、秘钥似乎都是不同的
2.如果您使用的是[https://github.com/chuyuewei/ChatGPT-API](https://github.com/chuyuewei/ChatGPT-API)，我可能需要为您手动调整，带您确认后会进行排期。届时您可以先使用[https://www.openai-hk.com/docs/getting-started.html](https://www.openai-hk.com/docs/getting-started.html)进行替代
3.如果您使用的是OpenAI-HK和它的官方api以及秘钥，请等待下一个开发版本推送。在实际测试中没有出现问题。

**Comment by xiaoyueyoqwq** [comment]
> 1.请您检查，您使用的gpt-3.5接口是使用https://github.com/chuyuewei/ChatGPT-API的，还是https://www.openai-hk.com/docs/getting-started.html 这两个的文档和接入方式、API地址、秘钥似乎都是不同的 2.如果您使用的是https://github.com/chuyuewei/ChatGPT-API，我可能需要为您手动调整，带您确认后会进行排期。届时您可以先使用https://www.openai-hk.com/docs/getting-started.html进行替代 3.如果您使用的是OpenAI-HK和它的官方api以及秘钥，请等待下一个开发版本推送。在实际测试中没有出现问题。

Hi, 早上好
我刚才再次确认并且测试了一下OpenAI-HK的api状态，使用了[第三方web-gpt网站](https://www.openai-hk.com/docs/useweb.html)进行调用测试，测试结果全部正常
mian.py方面还是报错428参数错误，也许我们该检查一下请求方法了？

**Comment by shuakami** [comment]
建议您等待大约20分钟后使用新开发版本进行测试。<3
在新开发版本中，您可以在config.yaml加入：
```yaml
log_level: DEBUG
debug: true
```
启用开发调试

**Comment by shuakami** [comment]
最新开发版已经更新，您可以下载https://github.com/shuakami/amyalmond_bot/tree/master/develop进行测试

**Comment by xiaoyueyoqwq** [comment]
> ```yaml
> log_level: DEBUG
> debug: true
> ```

测试结束，gemini-pro和gpt3.5-turbo均可兼容
辛苦啦😊

**Comment by shuakami** [comment]
我刚刚弄错了一个东西，现在我已经清空develop重新推送。您以后可以直接前往develop分支下载
https://github.com/shuakami/amyalmond_bot/tree/develop

**Comment by xiaoyueyoqwq** [comment]
> 我刚刚弄错了一个东西，现在我已经清空develop重新推送。您以后可以直接前往develop分支下载 https://github.com/shuakami/amyalmond_bot/tree/develop

没事，我手动打包上传到服务器上了，感谢🤗
