### ISSUE TITLE
[新手推荐] 运行报错“接口访问源IP不在白名单”和“在群内未见到机器人”问题

### ISSUE THREAD

**Issue by SuperGGB0** [shuakami/amyalmond_bot#22]
在配置完config.yaml，在启动main之后尝试获取admin，但是报错如下：
![image](https://github.com/user-attachments/assets/29aad6f0-d692-4d98-b938-2690d31f7497)
这个白名单是不知道是需要在哪加入，btw，我用的是deepseek配置如下（虽然我觉得影响不太大）
![image](https://github.com/user-attachments/assets/87706ec0-ef7e-401a-b7c9-f46f0605df28)

**Comment by shuakami** [comment]
您好。已经看到您的反馈。请稍等

**Comment by shuakami** [comment]
这个白名单指的是qq机器人管理端设置的ip白名单，您可以用ip网站获取自己的ip加白


![Image](https://github.com/user-attachments/assets/0805faec-86a0-46f5-b48d-c0537b89eb76)

**Comment by shuakami** [comment]
如果您修复了此问题请及时反馈

**Comment by SuperGGB0** [comment]
已经解决了，刚刚添加了白名单（感谢感谢🐂），但是我没找到怎么@机器人，我在此添加了自己的账号但是并未见到机器人。
![image](https://github.com/user-attachments/assets/9b1357cf-3a6a-43a4-9272-086bf934a834)

**Comment by SuperGGB0** [comment]
已经解决了，感谢佬

**Comment by shuakami** [comment]
好的。那关闭issue了，如果后续有问题可以随时提
祝您使用愉快

**Comment by shuakami** [comment]
> 已经解决了，刚刚添加了白名单（感谢感谢🐂），但是我没找到怎么@机器人，我在此添加了自己的账号但是并未见到机器人。
> [image.png (view on web)](https://github.com/user-attachments/assets/9b1357cf-3a6a-43a4-9272-086bf934a834)

关于您的这个反馈，请确认是否已经做了以下配置：
- 您已经正确配置了沙箱群
- 您在手机QQ内正确将机器人邀入群内（群机器人——最下滑——其他——添加您的机器人）
