### ISSUE TITLE
[FEATURE] third-party功能灵感建议（低优先级）

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [shuakami/amyalmond_bot#26]
最近上网冲浪发现了一个api网站：https://uapis.cn/
里面有很多很 **~...神经...~** 的api接口和功能，目前bot AI方面已经较为完善，我觉得我们可以考虑为bot添加一些奇奇怪怪的功能了 :P

**Comment by shuakami** [comment]
晚上好，我是天才叶小黑～

您的建议我很喜欢，并且看起来很有趣。所以我大概在2024/9/4可以开启这些新功能开发。大概2～7天完成。

稍后我会浏览一下您提供的文档。

**Comment by xiaoyueyoqwq** [comment]
> 晚上好，我是天才叶小黑～
> 
> 您的建议我很喜欢，并且看起来很有趣。所以我大概在2024/9/4开启这些新功能开发。大概2～7天完成。
> 
> 稍后我会浏览一下您提供的文档。

了解，不过收到最近开学的影响我可能无法及时提供Alpha Dev代码测试数据了，请您见谅
一旦有时间我会以最快速度尽可能收集多的数据反馈给您

**Comment by shuakami** [comment]
您好。看了一下，实现上应该是没有大问题的

**Comment by shuakami** [comment]
> 了解，不过收到最近开学的影响我可能无法及时提供Alpha Dev代码测试数据了，请您见谅
一旦有时间我会以最快速度尽可能收集多的数据反馈给您

好的。辛苦您了

**Comment by xiaoyueyoqwq** [comment]
> 您好。看了一下，实现上应该是没有大问题的

很高兴听到这个消息，我正在研究关于网易云点歌方面的api调用，目前我所看到的一些解决方案可能需要自行搭建api
如果您有服务器长期api托管需求可以直接跟我说即可，我手上有一台8c16g的年费服务器可以随时待命🚀

**Comment by shuakami** [comment]
您好。建议您可以使用YesPlayMusic前端+网易云api后端，直接发送链接给用户。
不过因为QQ官方的限制，如果点歌只能采用备案域名。

具体其他方法 如图片/语音我还在研究中。

**Comment by shuakami** [comment]
> 如果您有服务器长期api托管需求可以直接跟我说即可，我手上有一台8c16g的年费服务器可以随时待命🚀

您好。确实有这个想法，例如插件广场/管理机器人/云安全管理，都需要服务器和api还有域名。
但是因为我个人的原因，考虑到借用（托管至）您服务器可能会给您带来不必要的麻烦和安全问题。
所以我当前开发还是会尽量坚持使用本地部署/vercel这类。如果后续有实在无法解决的问题才会寻求您的物质帮助的～

**Comment by xiaoyueyoqwq** [comment]
> > 如果您有服务器长期api托管需求可以直接跟我说即可，我手上有一台8c16g的年费服务器可以随时待命🚀
> 
> 您好。确实有这个想法，例如插件广场/管理机器人/云安全管理，都需要服务器和api还有域名。
> 但是因为我个人的原因，考虑到借用（托管至）您服务器可能会给您带来不必要的麻烦和安全问题。
> 所以我当前开发还是会尽量坚持使用本地部署/vercel这类（如[检测更新的api–GitHub反代](https://api.amyalmond.mrsunny.top/)）。如果后续有实在无法解决的问题才会寻求您的物质帮助的～

讲个好消息，经过我这边的协调和努力我可以恢复日常的测试进度了，您可以随时发布更新，我这里可以随时提供测试结果和帮助❤️

**Comment by shuakami** [comment]
我很高兴听见您这么说。

**Comment by shuakami** [comment]
您好，目前您的此功能已经开始开发。

而在开发此功能之前需要先完成API系统的开发，否则后面再开发会比较复杂或者混沌。

**Comment by xiaoyueyoqwq** [comment]
> 您好，目前您的此功能已经开始开发。
> 
> 而在开发此功能之前需要先完成API系统的开发，否则后面再开发会比较复杂或者混沌。

备注个建议：可以给所有功能都加上cooldown_time设置，因为我这几天调查了一下其他bot服务的痛点，其中有很大一条就是**刷屏**；这也就导致了很多群聊挂壁理员都不得不在特殊情况下把bot移出群聊来缓解刷屏的情况，设置功能冷却时间更有利于管理员对于群聊的管理，提升用户体验

**Comment by shuakami** [comment]
您好。关于此问题，已经实装了ACE中的消息速率限制。后续会将会将分离配置，允许在配置文件中单独配置个人阈值和总体阈值

**Comment by shuakami** [comment]
您好， @xiaoyueyoqwq 。

现在的情况是插件系统已经基本开发完成了，接下来在准备前端相关的测试，为了安全性，还不能公开发布。
想问您有没有合适的时间可以帮我测试一下前端开发系统。

如果可以的话，您明天/后天什么时候有时间呢？

**Comment by xiaoyueyoqwq** [comment]
> 您好， @xiaoyueyoqwq 。
> 
> 现在的情况是插件系统已经基本开发完成了，接下来在准备前端相关的测试，为了安全性，还不能公开发布。
> 想问您有没有合适的时间可以帮我测试一下前端开发系统。
> 
> 如果可以的话，您明天/后天什么时候有时间呢？
> 
> <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 <3 

当然，明天晚上6点到10点我有时间可以进行测试，所有文件以压缩包形式发送到我个人邮箱即可：xiaoyueyoqwq@outlook.com

**Comment by shuakami** [comment]
好的。感谢您的回复。那我争取明天晚上7点前把所有文件以压缩包形式发送到您的个人邮箱。

---

> 另外很抱歉最终End Day与预期偏差很大
> ~因为我一个人的生产力始终有限~因为两个人的生产力始终有限（如果大模型算生产力的话）
> 但是这并不是我在抱怨，我实际上很享受这个过程..终于有事情干了
> 感谢您的等待

**Comment by xiaoyueyoqwq** [comment]
> 好的。感谢您的回复。那我争取明天晚上7点前把所有文件以压缩包形式发送到您的个人邮箱。
> 
> ---
> 
> > 另外很抱歉最终End Day与预期偏差很大
> > ~因为我一个人的生产力始终有限~ 因为两个人的生产力始终有限（如果大模型算生产力的话）
> > 但是这并不是我在抱怨，我实际上很享受这个过程..终于有事情干了
> > 感谢您的等待

对了，顺便一提我发现了一个很奇怪的现象：ES表格在正常运行情况下占用的内存到了惊人的8192mb，这属于正常情况还是配置有误？环境为Liunx Ubuntu

**Comment by shuakami** [comment]
您可以尝试降低此配置值，看一下内存占用是否减小




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shuakami/amyalmond_bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月8日(星期天) 上午8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shuakami/amyalmond_bot] [FEATURE] third-party功能灵感建议（低优先级） (Issue #26)





  
好的。感谢您的回复。那我争取明天晚上7点前把所有文件以压缩包形式发送到您的个人邮箱。
 
  
另外很抱歉最终End Day与预期偏差很大
 因为我一个人的生产力始终有限 因为两个人的生产力始终有限（如果大模型算生产力的话）
 但是这并不是我在抱怨，我实际上很享受这个过程..终于有事情干了
 感谢您的等待
   
对了，顺便一提我发现了一个很奇怪的现象：ES表格在正常运行情况下占用的内存到了惊人的8192mb，这属于正常情况还是配置有误？环境为Liunx Ubuntu
