### ISSUE TITLE
[BUG] configs文件夹配置文件检测问题

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [shuakami/amyalmond_bot#3]
当configs文件夹内没有config.yaml文件时控制台输出的提示是**其他报错**而不是类似**配置文件**丢失的报错，但是我大致检阅了一下main.py后注意到您已经为其添加了检测器，这些检测器可能并没有起到作用

我暂时认为这是一个bug，您可以先自行测试一下看看是否可以复现

**Comment by shuakami** [comment]
您好，已经在最新开发版本修复了此问题。请等待新版本推送。

**Comment by shuakami** [comment]
您好。请问此bug是否已经解决？

**Comment by xiaoyueyoqwq** [comment]
> 您好。请问此bug是否已经解决？

稍等，我去测试一下

**Comment by xiaoyueyoqwq** [comment]
> 您好。请问此bug是否已经解决？

一切正常，感谢
![image](https://github.com/user-attachments/assets/124eafdb-8270-438d-8831-761f419d06dd)
