### ISSUE TITLE
[SUGGEST] 自定义reply_message短语

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [shuakami/amyalmond_bot#5]
这个功能很有意思，但可以考虑一下在机器人可以正常返回api消息时禁用这个短句，并且单独一个设置文件格式来添加更多自定义短句
拜托，这真的很酷欸（嘻嘻

**Comment by shuakami** [comment]
预计在v1.1.5版本支持此功能，排期尚未确定，还请耐心等待 <3

**Comment by xiaoyueyoqwq** [comment]
> 预计在v1.1.5版本支持此功能，排期尚未确定，还请耐心等待 <3

okay, 辛苦啦

**Comment by shuakami** [comment]
排期已确定，详见Projects

**Comment by shuakami** [comment]
后面有可能将会使用插件方式支持(#16 )，您可以新开一个issue，标题写明新增插件。

另外内容请写上您需要的公益接口API列表以及文档，我会在项目开始时一一适配的。

辛苦您了

**Comment by xiaoyueyoqwq** [comment]
> 后面有可能将会使用插件方式支持(#16 )，您可以新开一个issue，标题写明新增插件。
> 
> 另外内容请写上您需要的公益接口API列表以及文档，我会在项目开始时一一适配的。
> 
> 辛苦您了

了解，我正在测试此功能，目前来说没有任何问题
感谢帮助，API接口我正在整理

**Comment by xiaoyueyoqwq** [comment]
暂无发现更多的新问题，此问题已经解决
