### ISSUE TITLE
[BUG] memory系统在第一次访问时可能抛出错误

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [shuakami/amyalmond_bot#8]
老规矩先上log: https://paste.ubuntu.com/p/syxCCjXqvv/
这是在手动删除一次memory.json后第一次对话抛出的错误，推测应该是memory.json没有主动生成或者生成了一个空文件导致脚本读取不到有效内容因此抛出的错误，在抛出错误后用户端并没有收到任何来自bot的消息推送

**Comment by shuakami** [comment]
了解。此功能之前就已经发现了，不过搞了这么多全忘了。
将会在下个新版本（Beta）跟 PreReleases一起修复此问题。

**Comment by shuakami** [comment]
您好，请尝试更新到最新开发版本`https://github.com/shuakami/amyalmond_bot/tree/develop`

**Comment by xiaoyueyoqwq** [comment]
> 您好，请尝试更新到最新开发版本`https://github.com/shuakami/amyalmond_bot/tree/develop`

这个问题我会一直监测，目前我已经更新了版本
如果我确认了问题已经解决，我会主动关闭issue
感谢帮助

**Comment by shuakami** [comment]
好的。修复将在明天中午左右跟正式版一同发布。

**Comment by shuakami** [comment]
您好，请更新到最新稳定版，然后测试此问题是否复现

**Comment by xiaoyueyoqwq** [comment]
> 您好，请更新到最新稳定版，然后测试此问题是否复现

已经同步上游更新，我会继续追踪此问题
感谢帮助

**Comment by xiaoyueyoqwq** [comment]
此问题已经修复
